### ISSUE TITLE
ETA on data and code release?

### ISSUE THREAD

**Issue by skelder** [computer-animation-perception-group/DeepDance#1]
Hello,

I am interested in testing out your project on custom dataset we collected ourselves.

I do understand that it has only been recent that you published the paper and the repository itself, but i was wondering if there are any ETA on when the dataset and training code will be released? 

also will you release the code you used to prepare your dataset?

Thank you

**Comment by guofeisun** [comment]
Thanks for your interest.
We are busy with some other works these days. We will release the training code, data preparation code, and data in September.

**Comment by skelder** [comment]
Thank you for reply.

Have a nice day!
